# Generated by Django 3.2.5 on 2022-06-18 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_completelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='completelist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='儲存日期'),
        ),
    ]
